Update deploy_to_huggingface.yml

diff --git a/.github/workflows/deploy_to_huggingface.yml b/.github/workflows/deploy_to_huggingface.yml
--- a/.github/workflows/deploy_to_huggingface.yml
+++ b/.github/workflows/deploy_to_huggingface.yml
@@ -19,14 +19,23 @@ jobs:
         python-version: "3.10"
 
     - name: Instalar Hugging Face CLI y actualizarla
-      run: |
-        pip install --upgrade huggingface_hub
-        huggingface-cli login --token ${{ secrets.HF_TOKEN }}
+      run: pip install --upgrade huggingface_hub
 
     - name: Crear el Space en Hugging Face
       run: |
-        huggingface-cli repo create Medical-RAGArch-System --type space --sdk docker --yes || echo "El Space ya existe, se continuará con la subida de archivos."
+        huggingface-cli repo create Medical-RAGArch-System --type space --yes || echo "El Space ya existe, se continuará con la subida de archivos."
 
     - name: Subir contenido al Space
+      run: huggingface-cli upload --repo-id "TU_USUARIO/Medical-RAGArch-System" --repo-type space --include-all-revision .
+      env:
+        HF_TOKEN: ${{ secrets.HF_TOKEN }}
+
+    - name: Post Configurar Python
+      if: failure()
       run: |
-        huggingface-cli repo upload Medical-RAGArch-System --recursive --commit-message "Deploy automático"
+        echo "Error al configurar Python"
+
+    - name: Post Checkout del código fuente
+      if: failure()
+      run: |
+        echo "Error en el checkout del código fuente"
